server:
  port: 8083 #内置Tomcat的设置端口号
spring:
  application:
    name: user  # 项目名称
  session:
    store-type: redis
logging:
  level:
    root: info
eureka: #强制不注册到注册服务器
  client:
    service-url:
      defaultZone: http://jie1:8761/eureka/
  #配置关闭自我保护，并按需配置Eureka Server清理无效节点的时间间隔。
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    
    
    
    
    
    
    
    
    
    
    
    
    
    

