server:
  port: 8080 #内置Tomcat的设置端口号
spring:
  application:
    name: eureka-client  # 项目名称
#security:
#  basic:
#    enabled: true # eureka 安全访问
#  user:
#    name: user
#    password: pa #用户名 密码
logging:
  level:
    root: warn
eureka: #强制不注册到注册服务器
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  #配置关闭自我保护，并按需配置Eureka Server清理无效节点的时间间隔。
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    
    
    
    
    
    
    
    
    
    
    
    
    
    

